# Generated by Django 5.2 on 2025-04-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.TextField(),
        ),
    ]
