# Generated by Django 5.2 on 2025-04-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='created_at',
            new_name='updated_at',
        ),
    ]
