# Generated by Django 5.2 on 2025-04-19 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_created_at_poll_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollchoices',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.poll'),
        ),
    ]
